name: Maman 14 CI (Ubuntu 24.04)

on:
  push:
    branches:
      - master
      - main
      paths:
        - 'maman14/**'
        - '.github/workflows/maman14-ci.yml'
      pull_request:
        branches:
          - master
          - main
        paths:
          - 'maman14/**'
          - '.github/workflows/maman14-ci.yml'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make git

      - name: Build Assembler
        run: |
          echo "=== Compiling Assembler ==="
          make clean && make
          echo "=== Build Successful ==="